local plates = require "lib.entities.plates"
local materials = require "lib.entities.materials"
local alloys    = require "lib.entities.alloys"

-- default enitites
-- can be used at start without any technologies
-- this table used for tech-tree rebuild algo

local default = {
    list = {
        [plates.iron] = {},
        [plates.copper] = {},
        [plates.lead] = {},
        [plates.tin] = {},
        [materials.glass] = {},
        [materials.stone] = {},
        [materials.wood] = {},
        [alloys.bronze] = {},
        -- TODO: refine list vvv
        -- ["iron-gear-wheel"] = { } ,
        ["wooden-chest"] = { } ,
        ["iron-chest"] = { } ,
        ["linked-chest"] = { } ,
        ["linked-belt"] = { } ,
        ["apm_dummy"] = { } ,
        ["apm_hidden_fuel"] = { } ,
        ["gem-ore"] = { } ,
        ["ruby-ore"] = { } ,
        ["sapphire-ore"] = { } ,
        ["emerald-ore"] = { } ,
        ["amethyst-ore"] = { } ,
        ["topaz-ore"] = { } ,
        ["diamond-ore"] = { } ,
        ["tin-ore"] = { } ,
        ["lead-ore"] = { } ,
        ["quartz"] = { } ,
        ["zinc-ore"] = { } ,
        ["gold-ore"] = { } ,
        ["bauxite-ore"] = { } ,
        ["rutile-ore"] = { } ,
        ["tungsten-ore"] = { } ,
        ["thorium-ore"] = { } ,
        ["nickel-ore"] = { } ,
        ["cobalt-ore"] = { } ,
        ["ruby-3"] = { } ,
        ["sapphire-3"] = { } ,
        ["emerald-3"] = { } ,
        ["amethyst-3"] = { } ,
        ["topaz-3"] = { } ,
        ["diamond-3"] = { } ,
        ["void"] = { } ,
        ["stone-mixing-furnace"] = { } ,
        ["wooden-board"] = { } ,
        -- ["bronze-pipe"] = { } ,
        ["apm_assembling_machine_0"] = { } ,
        ["apm_lab_0"] = { } ,
        ["apm_gearing"] = { } ,
        ["apm_mechanical_relay"] = { } ,
        ["apm_pistions"] = { } ,
        ["apm_simple_engine"] = { } ,
        ["apm_machine_frame_basic"] = { } ,
        ["apm_machine_frame_basic_used"] = { } ,
        ["apm_machine_frame_steam"] = { } ,
        ["apm_machine_frame_steam_used"] = { } ,
        ["apm_machine_frame_advanced"] = { } ,
        ["apm_machine_frame_advanced_used"] = { } ,
        ["bronze-gear-wheel"] = { } ,
        ["coal"] = { } ,
        ["sulfur"] = { } ,
        ["bronze-bearing"] = { } ,
        ["burner-mining-drill"] = {},
        ["burner-inserter"] = {},
        ["apm_burner_filter_inserter"] = {},
        ["silver-plate"] = {},
        ["firearm-magazine"] = {},
        ["apm_sea_water"] = {} ,
        ["apm_dirt_water"] = {},
        ["apm_discharged_battery"] = {},
        ["apm_discharged_lithium-ion-battery"] = {},
        ["apm_discharged_silver-zinc-battery"] = {},
        ["apm_shielded_nuclear_fuel_cell_used"] = {},
        ["apm_fuel_rod_thorium_active"] = {},
        ["apm_fuel_rod_neptunium_active"] = {},
        ["apm_breeder_uranium_active"] = {},
        ["apm_breeder_thorium_active"] = {},
        ["apm_breeder_container_worn"] = {},
        ["iron-ore"] = {},
        ["copper-ore"] = {},
        ["copper-cable"] = {},
        ["lithia-water"] = {},
        ["crude-oil"] = {},
    }
}

return default