local ores = {
    copper = 'copper-ore',
    iron = 'iron-ore',
    tin = 'tin-ore',
    lead = 'lead-ore',
    aluminium = 'bauxite-ore',
    zinc = 'zinc-ore',
    gold = 'gold-ore',
    cobalt = 'cobalt-ore',
    titanium = 'rutile-ore',
    silver = 'silver-ore',
    nickel = 'nickel-ore',
    tungsten = 'tungsten-ore',

    coal = 'coal',

    crushed = {
        basic = {
            iron = 'crushed-iron-ore',
            copper = 'crushed-copper-ore',
            tin = 'crushed-tin-ore',
            aluminium = 'crushed-bauxite-ore',
            zinc = 'crushed-zinc-ore',
            gold = 'crushed-gold-ore',
            cobalt = 'crushed-cobalt-ore',
            titanium = 'crushed-rutile-ore',
            silver = 'crushed-silver-ore',
            nickel = 'crushed-nickel-ore',
            tungsten = 'crushed-tungsten-ore',
            lead = 'crushed-lead-ore',
        },
        advance = {
            iron = 'advanced-crushed-iron-ore',
            copper = 'advanced-crushed-copper-ore',
            tin = 'advanced-crushed-tin-ore',
            aluminium = 'advanced-crushed-bauxite-ore',
            zinc = 'advanced-crushed-zinc-ore',
            gold = 'advanced-crushed-gold-ore',
            cobalt = 'advanced-crushed-cobalt-ore',
            titanium = 'advanced-crushed-rutile-ore',
            silver = 'advanced-crushed-silver-ore',
            nickel = 'advanced-crushed-nickel-ore',
            tungsten = 'advanced-crushed-tungsten-ore',
            lead = 'advanced-crushed-lead-ore',
        },
    },

    enriched = {
        basic = {
            copper = 'enriched-copper-ore',
            iron = 'enriched-iron-ore',
            tin = 'enriched-tin-ore',
            lead = 'enriched-lead-ore',
            aluminium = 'enriched-bauxite-ore',
            zinc = 'enriched-zinc-ore',
            gold = 'enriched-gold-ore',
            cobalt = 'enriched-cobalt-ore',
            titanium = 'enriched-rutile-ore',
            silver = 'enriched-silver-ore',
            nickel = 'enriched-nickel-ore',
            tungsten = 'enriched-tungsten-ore',
        },
        advance = {
            copper = 'advanced-enriched-copper-ore',
            iron = 'advanced-enriched-iron-ore',
            tin = 'advanced-enriched-tin-ore',
            lead = 'advanced-enriched-lead-ore',
            aluminium = 'advanced-enriched-bauxite-ore',
            zinc = 'advanced-enriched-zinc-ore',
            gold = 'advanced-enriched-gold-ore',
            cobalt = 'advanced-enriched-cobalt-ore',
            titanium = 'advanced-enriched-rutile-ore',
            silver = 'advanced-enriched-silver-ore',
            nickel = 'advanced-enriched-nickel-ore',
            tungsten = 'advanced-enriched-tungsten-ore',
        },
    },
}

return ores