if apm.bob_rework.lib == nil then apm.bob_rework.lib = {} end
if apm.bob_rework.lib.entities == nil then apm.bob_rework.lib.entities = {} end

apm.bob_rework.lib.entities.bronze = 'bronze-alloy'
apm.bob_rework.lib.entities.iron = 'iron-plate'
apm.bob_rework.lib.entities.tin = 'tin-plate'
apm.bob_rework.lib.entities.copper = 'copper-plate'
apm.bob_rework.lib.entities.brass = 'brass-alloy'
apm.bob_rework.lib.entities.steel = 'steel-plate'
apm.bob_rework.lib.entities.nickel = 'nickel-plate'
apm.bob_rework.lib.entities.invar = 'invar-alloy'
apm.bob_rework.lib.entities.siliconNitride = 'silicon-nitride'
apm.bob_rework.lib.entities.aluminium = 'aluminium-plate'
apm.bob_rework.lib.entities.cobaltSteel = 'cobalt-steel-alloy'
apm.bob_rework.lib.entities.tungsten = 'tungsten-plate'
apm.bob_rework.lib.entities.titanium = 'titanium-plate'
apm.bob_rework.lib.entities.tungstenCarbide = 'tungsten-carbide'
apm.bob_rework.lib.entities.copperTungsten = 'copper-tungsten-alloy'
apm.bob_rework.lib.entities.silver = 'silver-plate'
apm.bob_rework.lib.entities.gold = 'gold-plate'
apm.bob_rework.lib.entities.lead = 'lead-plate'
apm.bob_rework.lib.entities.nitinol = 'nitinol-alloy'
apm.bob_rework.lib.entities.lowDS = 'low-density-structure'
apm.bob_rework.lib.entities.gunMetal = 'gunmetal-alloy'