require('util')
local science = require('lib.entities.science')

-- energy reactor

local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")
local kr_crash_site_icons_path = '__apm_bob_rework_ldinc__/graphics/icons/krastorio/entities/crash-site/'
local kr_crash_site_sprites_path = '__apm_bob_rework_ldinc__/graphics/entities/krastorio/crash-site/'
local power = '2500'

data:extend({
    {
        type = "electric-energy-interface",
        name = "kr-crash-site-generator",
        localised_name = { "entity-name.kr-damaged-ship-reactor" },
        localised_description = { "entity-description.kr-crash-site-building" },
        icon = kr_crash_site_icons_path .. "crash-site-generator.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = { "placeable-player", "player-creation", "hidden", "not-rotatable" },
        map_color = { r = 0, g = 0.365, b = 0.58, a = 1 },
        max_health = 150,
        resistances = {
            { type = "fire", percent = 100 },
            { type = "impact", percent = 60 },
            { type = "physical", percent = 50 },
        },
        corpse = "medium-remnants",
        minable = {
            mining_time = 4,
            results = {
                { type = "item", name = "iron-plate", amount_min = 5, amount_max = 13, probability = 1 },
                { type = "item", name = "copper-cable", amount_min = 4, amount_max = 8, probability = 1 },
                { type = "item", name = "iron-gear-wheel", amount_min = 3, amount_max = 5, probability = 0.75 },
                { type = "item", name = "electronic-circuit", amount_min = 2, amount_max = 3, probability = 0.75 },
                { type = "item", name = "kr-sentinel", amount_min = 1, amount_max = 2, probability = 0.50 },
            },
            mining_particle = "shell-particle",
        },
        damaged_trigger_effect = hit_effects.entity(),
        collision_box = { { -1.5, -0.9 }, { 0.9, 0.9 } },
        selection_box = { { -1.5, -0.9 }, { 0.9, 0.9 } },
        allow_copy_paste = false,
        energy_source = {
            type = "electric",
            buffer_capacity = power .. 'kJ',
            usage_priority = "primary-output",
            input_flow_limit = "0kW",
            output_flow_limit = power .. "kW",
        },
        energy_production = power .. "kW",
        energy_usage = "0kW",
        light = {
            intensity = 0.24,
            size = 1,
            color = { r = 0.196, g = 0.658, b = 0.650 },
            shift = { 64 / 64, -140 / 64 },
        },
        continuous_animation = true,
        integration_patch_render_layer = "decals",
        integration_patch = {
            filename = kr_crash_site_sprites_path .. "generator/crash-site-generator-ground.png",
            width = 192,
            height = 180,
            shift = util.by_pixel(-28, -38),
            frame_count = 1,
            line_length = 1,
            hr_version = {
                filename = kr_crash_site_sprites_path .. "generator/hr-crash-site-generator-ground.png",
                width = 384,
                height = 360,
                shift = util.by_pixel(-28, -38),
                frame_count = 1,
                line_length = 1,
                scale = 0.5,
            },
        },
        animation = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path .. "generator/crash-site-generator.png",
                    width = 142,
                    height = 128,
                    frame_count = 5,
                    line_length = 5,
                    repeat_count = 16,
                    shift = util.by_pixel(-10, -24),
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "generator/hr-crash-site-generator.png",
                        width = 286,
                        height = 252,
                        frame_count = 5,
                        line_length = 5,
                        repeat_count = 16,
                        shift = util.by_pixel(-11, -23),
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "generator/crash-site-generator-beams.png",
                    width = 48,
                    height = 116,
                    frame_count = 16,
                    line_length = 4,
                    repeat_count = 5,
                    shift = util.by_pixel(24, -30),
                    draw_as_glow = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "generator/hr-crash-site-generator-beams.png",
                        width = 224,
                        height = 232,
                        frame_count = 16,
                        line_length = 4,
                        repeat_count = 5,
                        shift = util.by_pixel(-8, -30),
                        draw_as_glow = true,
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "generator/crash-site-generator-beams-light.png",
                    width = 48,
                    height = 116,
                    frame_count = 16,
                    line_length = 4,
                    repeat_count = 5,
                    shift = util.by_pixel(24, -30),
                    draw_as_light = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "generator/hr-crash-site-generator-beams-light.png",
                        width = 224,
                        height = 232,
                        frame_count = 16,
                        line_length = 4,
                        repeat_count = 5,
                        shift = util.by_pixel(-8, -30),
                        draw_as_light = true,
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "generator/crash-site-generator-shadow.png",
                    width = 236,
                    height = 78,
                    frame_count = 1,
                    line_length = 1,
                    repeat_count = 80,
                    shift = util.by_pixel(26, 4),
                    draw_as_shadow = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "generator/hr-crash-site-generator-shadow.png",
                        width = 474,
                        height = 152,
                        frame_count = 1,
                        line_length = 1,
                        repeat_count = 80,
                        draw_as_shadow = true,
                        shift = util.by_pixel(25, 5),
                        scale = 0.5,
                    },
                },
            },
        },
        vehicle_impact_sound = sounds.generic_impact,
    },
})

-- spaceship lab

data:extend({
    {
        type = "lab",
        name = "kr-crash-site-lab-repaired",
        localised_name = { "entity-name.kr-damaged-ship-research-computer" },
        localised_description = { "entity-description.kr-crash-site-building" },
        has_backer_name = false,
        icon = kr_crash_site_icons_path .. "crash-site-lab-repaired.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = { "placeable-player", "player-creation", "hidden", "not-rotatable" },
        map_color = { r = 0, g = 0.365, b = 0.58, a = 1 },
        max_health = 150,
        resistances = {
            { type = "fire", percent = 100 },
            { type = "impact", percent = 60 },
            { type = "physical", percent = 50 },
        },
        corpse = "big-remnants",
        minable = {
            mining_time = 4,
            results = {
                { type = "item", name = "iron-plate", amount_min = 5, amount_max = 13, probability = 1 },
                { type = "item", name = "copper-cable", amount_min = 4, amount_max = 8, probability = 1 },
                { type = "item", name = "iron-gear-wheel", amount_min = 3, amount_max = 5, probability = 0.75 },
                { type = "item", name = "electronic-circuit", amount_min = 2, amount_max = 3, probability = 0.75 },
                { type = "item", name = "kr-sentinel", amount_min = 1, amount_max = 2, probability = 0.50 },
            },
            mining_particle = "shell-particle",
        },
        dying_explosion = "medium-explosion",
        damaged_trigger_effect = hit_effects.entity(),
        collision_box = { { -2.2, -1.2 }, { 2.2, 1.2 } },
        selection_box = { { -2.5, -1.5 }, { 2.5, 1.5 } },
        entity_info_icon_shift = util.by_pixel(32, 0),
        light = {
            intensity = 0.34,
            size = 3,
            color = { r = 0.196, g = 0.658, b = 0.650 },
            shift = { 1.5, 0.5 },
        },
        integration_patch_render_layer = "decals",
        integration_patch = {
            filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-ground.png",
            width = 352,
            height = 170,
            shift = util.by_pixel(-48, 12),
            frame_count = 1,
            line_length = 1,
            hr_version = {
                filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-ground.png",
                width = 700,
                height = 344,
                shift = util.by_pixel(-49, 11),
                frame_count = 1,
                line_length = 1,
                scale = 0.5,
            },
        },
        on_animation = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-repaired.png",
                    width = 244,
                    height = 126,
                    frame_count = 1,
                    line_length = 1,
                    repeat_count = 24,
                    animation_speed = 1 / 3,
                    shift = util.by_pixel(-18, 14),
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-repaired.png",
                        width = 488,
                        height = 252,
                        frame_count = 1,
                        line_length = 1,
                        repeat_count = 24,
                        animation_speed = 1 / 3,
                        shift = util.by_pixel(-18, 14),
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-repaired-beams.png",
                    width = 68,
                    height = 50,
                    frame_count = 24,
                    line_length = 6,
                    animation_speed = 1 / 3,
                    shift = util.by_pixel(36, -20),
                    draw_as_glow = true,
                    blend_mode = "additive",
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-repaired-beams.png",
                        width = 130,
                        height = 100,
                        frame_count = 24,
                        line_length = 6,
                        animation_speed = 1 / 3,
                        shift = util.by_pixel(37, -20),
                        draw_as_glow = true,
                        blend_mode = "additive",
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-repaired-beams-light.png",
                    width = 68,
                    height = 50,
                    frame_count = 24,
                    line_length = 6,
                    animation_speed = 1 / 3,
                    shift = util.by_pixel(36, -20),
                    draw_as_light = true,
                    blend_mode = "additive",
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-repaired-beams-light.png",
                        width = 130,
                        height = 100,
                        frame_count = 24,
                        line_length = 6,
                        animation_speed = 1 / 3,
                        shift = util.by_pixel(37, -20),
                        draw_as_light = true,
                        blend_mode = "additive",
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-repaired-shadow.png",
                    width = 350,
                    height = 148,
                    frame_count = 1,
                    line_length = 1,
                    repeat_count = 24,
                    animation_speed = 1 / 3,
                    shift = util.by_pixel(-12, 12),
                    draw_as_shadow = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-repaired-shadow.png",
                        width = 696,
                        height = 302,
                        frame_count = 1,
                        line_length = 1,
                        repeat_count = 24,
                        animation_speed = 1 / 3,
                        shift = util.by_pixel(-11, 12),
                        scale = 0.5,
                        draw_as_shadow = true,
                    },
                },
            },
        },
        off_animation = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-repaired.png",
                    width = 244,
                    height = 126,
                    frame_count = 1,
                    line_length = 1,
                    repeat_count = 24,
                    animation_speed = 1 / 3,
                    shift = util.by_pixel(-18, 14),
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-repaired.png",
                        width = 488,
                        height = 252,
                        frame_count = 1,
                        line_length = 1,
                        repeat_count = 24,
                        animation_speed = 1 / 3,
                        shift = util.by_pixel(-18, 14),
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "lab/crash-site-lab-repaired-shadow.png",
                    width = 350,
                    height = 148,
                    frame_count = 1,
                    line_length = 1,
                    repeat_count = 24,
                    animation_speed = 1 / 3,
                    shift = util.by_pixel(-12, 12),
                    draw_as_shadow = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "lab/hr-crash-site-lab-repaired-shadow.png",
                        width = 696,
                        height = 302,
                        frame_count = 1,
                        line_length = 1,
                        repeat_count = 24,
                        animation_speed = 1 / 3,
                        shift = util.by_pixel(-11, 12),
                        scale = 0.5,
                        draw_as_shadow = true,
                    },
                },
            },
        },
        working_sound = {
            sound = {
                filename = "__base__/sound/lab.ogg",
                volume = 0.7,
            },
            audible_distance_modifier = 0.7,
            fade_in_ticks = 4,
            fade_out_ticks = 20,
        },
        vehicle_impact_sound = sounds.generic_impact,
        open_sound = sounds.machine_open,
        close_sound = sounds.machine_close,
        energy_source = {
            type = "electric",
            usage_priority = "secondary-input",
            emissions_per_minute = 4,
        },
        energy_usage = "60kW",
        researching_speed = 2,
        inputs = {
            science.industrial,
            science.steam,
            science.automation,
            science.military,
        },
    },
})

-- assembler 1 (crusher & sieve machine)

data:extend({
    {
        type = "assembling-machine",
        name = "kr-crash-site-assembling-machine-1-repaired",
        localised_name = { "entity-name.kr-damaged-ship-assembler" },
        localised_description = { "entity-description.kr-crash-site-building" },
        has_backer_name = false,
        icon = kr_crash_site_icons_path .. "crash-site-assembling-machine-1-repaired.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = { "placeable-player", "player-creation", "hidden", "not-rotatable" },
        map_color = { r = 0, g = 0.365, b = 0.58, a = 1 },
        max_health = 300,
        corpse = "big-remnants",
        minable = {
            mining_time = 4,
            results = {
                { type = "item", name = "iron-plate", amount_min = 5, amount_max = 13, probability = 1 },
                { type = "item", name = "copper-cable", amount_min = 4, amount_max = 8, probability = 1 },
                { type = "item", name = "iron-gear-wheel", amount_min = 3, amount_max = 5, probability = 0.75 },
                { type = "item", name = "electronic-circuit", amount_min = 2, amount_max = 3, probability = 0.75 },
                { type = "item", name = "kr-sentinel", amount_min = 1, amount_max = 2, probability = 0.50 },
            },
            mining_particle = "shell-particle",
        },
        dying_explosion = "medium-explosion",
        damaged_trigger_effect = hit_effects.entity(),
        resistances = {
            { type = "fire", percent = 100 },
            { type = "impact", percent = 60 },
            { type = "physical", percent = 50 },
        },
        collision_box = { { -1.2, -0.7 }, { 1.2, 0.7 } },
        selection_box = { { -1.5, -1 }, { 1.5, 1 } },
        alert_icon_shift = util.by_pixel(-3, -12),
        integration_patch_render_layer = "decals",
        integration_patch = {
            filename = kr_crash_site_sprites_path .. "assembling-machine/crash-site-assembling-machine-1-ground.png",
            width = 208,
            height = 116,
            shift = util.by_pixel(-24, 12),
            frame_count = 1,
            line_length = 1,
            hr_version = {
                filename = kr_crash_site_sprites_path ..
                    "assembling-machine/hr-crash-site-assembling-machine-1-ground.png",
                width = 446,
                height = 234,
                shift = util.by_pixel(-31, 12),
                frame_count = 1,
                line_length = 1,
                scale = 0.5,
            },
        },
        animation = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path ..
                        "assembling-machine/crash-site-assembling-machine-1-repaired.png",
                    width = 142,
                    height = 92,
                    frame_count = 20,
                    line_length = 5,
                    shift = util.by_pixel(-12, 2),
                    animation_speed = kr_crash_site_assembling_machine_1_repaired_animation_speed,
                    hr_version = {
                        filename = kr_crash_site_sprites_path
                            .. "assembling-machine/hr-crash-site-assembling-machine-1-repaired.png",
                        width = 282,
                        height = 182,
                        frame_count = 20,
                        line_length = 5,
                        shift = util.by_pixel(-12, 3),
                        animation_speed = kr_crash_site_assembling_machine_1_repaired_animation_speed,
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path
                        .. "assembling-machine/crash-site-assembling-machine-1-repaired-shadow.png",
                    width = 140,
                    height = 84,
                    frame_count = 20,
                    line_length = 5,
                    draw_as_shadow = true,
                    shift = util.by_pixel(4, 6),
                    animation_speed = kr_crash_site_assembling_machine_1_repaired_animation_speed,
                    hr_version = {
                        filename = kr_crash_site_sprites_path
                            .. "assembling-machine/hr-crash-site-assembling-machine-1-repaired-shadow.png",
                        width = 278,
                        height = 168,
                        frame_count = 20,
                        line_length = 5,
                        draw_as_shadow = true,
                        shift = util.by_pixel(4, 6),
                        animation_speed = kr_crash_site_assembling_machine_1_repaired_animation_speed,
                        scale = 0.5,
                    },
                },
            },
        },
        working_visualisations = {
            {
                animation = {
                    filename = kr_crash_site_sprites_path
                        .. "assembling-machine/crash-site-assembling-machine-1-repaired-light.png",
                    width = 78,
                    height = 64,
                    frame_count = 20,
                    line_length = 5,
                    shift = util.by_pixel(10, -10),
                    draw_as_glow = true,
                    blend_mode = "additive",
                    animation_speed = kr_crash_site_assembling_machine_1_repaired_animation_speed,
                    hr_version = {
                        filename = kr_crash_site_sprites_path
                            .. "assembling-machine/hr-crash-site-assembling-machine-1-repaired-light.png",
                        width = 162,
                        height = 120,
                        frame_count = 20,
                        line_length = 5,
                        shift = util.by_pixel(12, -8),
                        draw_as_glow = true,
                        blend_mode = "additive",
                        animation_speed = kr_crash_site_assembling_machine_1_repaired_animation_speed,
                        scale = 0.5,
                    },
                },
            },
        },
        crafting_categories = { "apm_crusher", "apm_sifting_0" },
        crafting_speed = 0.5,
        energy_source = {
            type = "electric",
            usage_priority = "secondary-input",
            emissions_per_minute = 4,
        },
        energy_usage = "90kW",
        ingredient_count = 2,
        open_sound = sounds.machine_open,
        close_sound = sounds.machine_close,
        vehicle_impact_sound = sounds.generic_impact,
        working_sound = {
            sound = {
                {
                    filename = "__base__/sound/assembling-machine-repaired-1.ogg",
                    volume = 0.8,
                },
            },
        },
    },
})

-- assembler 2 (assembler)
data:extend({
    {
        type = "assembling-machine",
        name = "kr-crash-site-assembling-machine-2-repaired",
        localised_name = { "entity-name.kr-damaged-ship-assembler" },
        localised_description = { "entity-description.kr-crash-site-building" },
        has_backer_name = false,
        icon = kr_crash_site_icons_path .. "crash-site-assembling-machine-2-repaired.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = { "placeable-player", "player-creation", "hidden", "not-rotatable" },
        map_color = { r = 0, g = 0.365, b = 0.58, a = 1 },
        max_health = 300,
        corpse = "big-remnants",
        minable = {
            mining_time = 4,
            results = {
                { type = "item", name = "iron-plate", amount_min = 5, amount_max = 13, probability = 1 },
                { type = "item", name = "copper-cable", amount_min = 4, amount_max = 8, probability = 1 },
                { type = "item", name = "iron-gear-wheel", amount_min = 3, amount_max = 5, probability = 0.75 },
                { type = "item", name = "electronic-circuit", amount_min = 2, amount_max = 3, probability = 0.75 },
                { type = "item", name = "kr-sentinel", amount_min = 1, amount_max = 2, probability = 0.50 },
            },
            mining_particle = "shell-particle",
        },
        dying_explosion = "medium-explosion",
        damaged_trigger_effect = hit_effects.entity(),
        resistances = {
            { type = "fire", percent = 100 },
            { type = "impact", percent = 60 },
            { type = "physical", percent = 50 },
        },
        collision_box = { { -0.7, -1.2 }, { 0.7, 1.2 } },
        selection_box = { { -1, -1.5 }, { 1, 1.5 } },
        alert_icon_shift = util.by_pixel(-3, -12),
        integration_patch_render_layer = "decals",
        integration_patch = {
            filename = kr_crash_site_sprites_path .. "assembling-machine/crash-site-assembling-machine-2-ground.png",
            width = 146,
            height = 106,
            shift = util.by_pixel(-8, -4),
            frame_count = 1,
            line_length = 1,
            hr_version = {
                filename = kr_crash_site_sprites_path ..
                    "assembling-machine/hr-crash-site-assembling-machine-2-ground.png",
                width = 290,
                height = 238,
                shift = util.by_pixel(-8, -10),
                frame_count = 1,
                line_length = 1,
                scale = 0.5,
            },
        },
        animation = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path ..
                        "assembling-machine/crash-site-assembling-machine-2-repaired.png",
                    width = 100,
                    height = 98,
                    frame_count = 20,
                    line_length = 5,
                    shift = util.by_pixel(-4, -10),
                    animation_speed = 2,
                    hr_version = {
                        filename = kr_crash_site_sprites_path
                            .. "assembling-machine/hr-crash-site-assembling-machine-2-repaired.png",
                        width = 198,
                        height = 200,
                        frame_count = 20,
                        line_length = 5,
                        shift = util.by_pixel(-4, -11),
                        animation_speed = 2,
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path
                        .. "assembling-machine/crash-site-assembling-machine-2-repaired-shadow.png",
                    width = 106,
                    height = 86,
                    frame_count = 20,
                    line_length = 5,
                    draw_as_shadow = true,
                    shift = util.by_pixel(2, -8),
                    animation_speed = 2,
                    hr_version = {
                        filename = kr_crash_site_sprites_path
                            .. "assembling-machine/hr-crash-site-assembling-machine-2-repaired-shadow.png",
                        width = 208,
                        height = 174,
                        frame_count = 20,
                        line_length = 5,
                        draw_as_shadow = true,
                        shift = util.by_pixel(3, -9),
                        animation_speed = 2,
                        scale = 0.5,
                    },
                },
            },
        },
        working_visualisations = {
            {
                animation = {
                    filename = kr_crash_site_sprites_path
                        .. "assembling-machine/crash-site-assembling-machine-2-repaired-light.png",
                    width = 84,
                    height = 62,
                    frame_count = 20,
                    line_length = 5,
                    shift = util.by_pixel(-8, -6),
                    draw_as_glow = true,
                    blend_mode = "additive",
                    animation_speed = 2,
                    hr_version = {
                        filename = kr_crash_site_sprites_path
                            .. "assembling-machine/hr-crash-site-assembling-machine-2-repaired-light.png",
                        width = 174,
                        height = 124,
                        frame_count = 20,
                        line_length = 5,
                        shift = util.by_pixel(-7, -4),
                        draw_as_glow = true,
                        blend_mode = "additive",
                        animation_speed = 2,
                        scale = 0.5,
                    },
                },
            },
        },
        crafting_categories = { "crafting", "basic-crafting" },
        crafting_speed = 0.25,
        energy_source = {
            type = "electric",
            usage_priority = "secondary-input",
            emissions_per_minute = 4,
        },
        energy_usage = "90kW",
        ingredient_count = 2,
        open_sound = sounds.machine_open,
        close_sound = sounds.machine_close,
        vehicle_impact_sound = sounds.generic_impact,
        working_sound = {
            sound = {
                {
                    filename = "__base__/sound/assembling-machine-repaired-1.ogg",
                    volume = 0.8,
                },
            },
            fade_in_ticks = 4,
            fade_out_ticks = 20,
        },
    },
})

-- chest 1
data:extend({
    {
        type = "container",
        name = "kr-crash-site-chest-1",
        localised_name = { "entity-name.crash-site-chest-1" },
        localised_description = { "entity-description.kr-crash-site-building" },
        icon = kr_crash_site_icons_path .. "crash-site-chest.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = { "placeable-player", "player-creation", "hidden", "not-rotatable" },
        max_health = 350,
        corpse = "small-remnants",
        minable = {
            mining_time = 2,
            results = {
                { type = "item", name = "iron-plate", amount_min = 1, amount_max = 2, probability = 0.70 },
                { type = "item", name = "copper-cable", amount_min = 0, amount_max = 2, probability = 0.40 },
                { type = "item", name = "iron-gear-wheel", amount_min = 0, amount_max = 2, probability = 0.40 },
                { type = "item", name = "electronic-circuit", amount_min = 0, amount_max = 2, probability = 0.20 },
                { type = "item", name = "kr-sentinel", amount_min = 0, amount_max = 2, probability = 0.10 },
            },
            mining_particle = "shell-particle",
        },
        damaged_trigger_effect = hit_effects.entity(),
        open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.5 },
        close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.5 },
        resistances = {
            { type = "fire", percent = 100 },
            { type = "impact", percent = 60 },
            { type = "physical", percent = 50 },
        },
        collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
        selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
        fast_replaceable_group = "container",
        inventory_size = 5,
        vehicle_impact_sound = sounds.generic_impact,
        integration_patch = {
            filename = kr_crash_site_sprites_path .. "chests/crash-site-chest-1-ground.png",
            width = 111,
            height = 73,
            shift = util.by_pixel(-6, 12),
            frame_count = 1,
            line_length = 1,
            hr_version = {
                filename = kr_crash_site_sprites_path .. "chests/hr-crash-site-chest-1-ground.png",
                width = 220,
                height = 148,
                shift = util.by_pixel(-6, 12),
                frame_count = 1,
                line_length = 1,
                scale = 0.5,
            },
        },
        picture = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path .. "chests/crash-site-chest-1.png",
                    priority = "extra-high",
                    width = 61,
                    height = 39,
                    shift = util.by_pixel(2, 8),
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "chests/hr-crash-site-chest-1.png",
                        priority = "extra-high",
                        width = 120,
                        height = 76,
                        shift = util.by_pixel(2, 8),
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "chests/crash-site-chest-1-shadow.png",
                    priority = "extra-high",
                    width = 99,
                    height = 67,
                    shift = util.by_pixel(-8, 2),
                    draw_as_shadow = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "chests/hr-crash-site-chest-1-shadow.png",
                        priority = "extra-high",
                        width = 210,
                        height = 128,
                        shift = util.by_pixel(-2, 3),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
        },
    },
})

-- chest 2
data:extend({
    {
        type = "container",
        name = "kr-crash-site-chest-2",
        localised_name = { "entity-name.crash-site-chest-2" },
        localised_description = { "entity-description.kr-crash-site-building" },
        icon = kr_crash_site_icons_path .. "crash-site-chest.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = { "placeable-player", "player-creation", "hidden", "not-rotatable" },
        max_health = 350,
        corpse = "small-remnants",
        minable = {
            mining_time = 2,
            results = {
                { type = "item", name = "iron-plate", amount_min = 1, amount_max = 2, probability = 0.70 },
                { type = "item", name = "copper-cable", amount_min = 0, amount_max = 2, probability = 0.40 },
                { type = "item", name = "iron-gear-wheel", amount_min = 0, amount_max = 2, probability = 0.40 },
                { type = "item", name = "electronic-circuit", amount_min = 0, amount_max = 2, probability = 0.20 },
                { type = "item", name = "kr-sentinel", amount_min = 0, amount_max = 2, probability = 0.10 },
            },
            mining_particle = "shell-particle",
        },
        damaged_trigger_effect = hit_effects.entity(),
        open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.43 },
        close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.43 },
        resistances = {
            { type = "fire", percent = 100 },
            { type = "impact", percent = 60 },
            { type = "physical", percent = 50 },
        },
        collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
        selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
        fast_replaceable_group = "container",
        inventory_size = 5,
        vehicle_impact_sound = sounds.generic_impact,
        integration_patch = {
            filename = kr_crash_site_sprites_path .. "chests/crash-site-chest-2-ground.png",
            width = 111,
            height = 95,
            shift = util.by_pixel(-12, 4),
            frame_count = 1,
            line_length = 1,
            hr_version = {
                filename = kr_crash_site_sprites_path .. "chests/hr-crash-site-chest-2-ground.png",
                width = 218,
                height = 186,
                shift = util.by_pixel(-10, 5),
                frame_count = 1,
                line_length = 1,
                scale = 0.5,
            },
        },
        picture = {
            layers = {
                {
                    filename = kr_crash_site_sprites_path .. "chests/crash-site-chest-2.png",
                    priority = "extra-high",
                    width = 59,
                    height = 45,
                    shift = util.by_pixel(0, 8),
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "chests/hr-crash-site-chest-2.png",
                        priority = "extra-high",
                        width = 116,
                        height = 88,
                        shift = util.by_pixel(0, 8),
                        scale = 0.5,
                    },
                },
                {
                    filename = kr_crash_site_sprites_path .. "chests/crash-site-chest-2-shadow.png",
                    priority = "extra-high",
                    width = 95,
                    height = 65,
                    shift = util.by_pixel(0, 4),
                    draw_as_shadow = true,
                    hr_version = {
                        filename = kr_crash_site_sprites_path .. "chests/hr-crash-site-chest-2-shadow.png",
                        priority = "extra-high",
                        width = 188,
                        height = 126,
                        shift = util.by_pixel(0, 5),
                        draw_as_shadow = true,
                        scale = 0.5,
                    },
                },
            },
        },
    },
})
